### PR TITLE
#2536 Fix race condition in bsonmapper

### LINKED ISSUE #2536: [BUG] Race condition in BsonMapper
**Version**
LiteDB 5.0.21
.NET 8.0.401
Linux (Fedora 38)

**Describe the bug**
Specifically, what I see is an occasional stacktrace:

```
System.NotSupportedException : Member Id not found on BsonMapper for type MyNamespace.MyType
 Stack Trace:
at LiteDB.LinqExpressionVisitor.ResolveMember(MemberInfo member)
at LiteDB.LinqExpressionVisitor.VisitMember(MemberExpression node)
at LiteDB.LinqExpressionVisitor.ResolvePattern(String pattern, Expression obj, IList`1 args)
at LiteDB.LinqExpressionVisitor.VisitMethodCall(MethodCallExpression node)
at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
at LiteDB.LinqExpressionVisitor.VisitLambda[T](Expression`1 node)
at LiteDB.LinqExpressionVisitor.Resolve(Boolean predicate)
at LiteDB.BsonMapper.GetExpression[T,K](Expression`1 predicate)
at LiteDB.LiteCollection`1.DeleteMany(Expression`1 predicate)
```

when running an expression like

```c#
collection.DeleteMany(item => idsToDelete.Contains(item.Id))
```

**Code to Reproduce**
I cannot reproduce this consistently, it only happens once in a while, likely while I am running multiple concurrent transactions not against the same collection, but using the same types.

I believe this is a race condition caused by #2493, here's the possible race I see that this PR introduced:

 - Thread A enters `GetEntityMapper` [here](https://github.com/mbdavid/LiteDB/blame/391cc9318c5be6e56cb71b3ce14b1ed9cb324763/LiteDB/Client/Mapper/BsonMapper.cs#L238), and does not find the mapper.
 - Thread A calls `BuildAddEntityMapper`, and goes past [this line](https://github.com/mbdavid/LiteDB/blame/391cc9318c5be6e56cb71b3ce14b1ed9cb324763/LiteDB/Client/Mapper/BsonMapper.cs#L257), adding an entity mapper to the _entities dictionary.
 - Thread A is preempted by thread B, which enters `GetEntityMapper`.
 - Thread B _finds_ a mapper and returns, but this mapper won't work, as it has not yet been populated with fields, resulting in the stacktrace above.

This code has existed for a long time, and this issue only started after updating to the latest version, which contains this fix. There may be a different cause, though my trace above seems plausible.

### PR DESCRIPTION
**Pull request by JKamsker**
Fixes https://github.com/mbdavid/LiteDB/issues/2536

### CODE REVIEW

File: LiteDB/Client/Mapper/BsonMapper.cs [hunk 1]
```diff
@@ -235,13 +242,30 @@ internal EntityMapper GetEntityMapper(Type type)
...
             {
-                lock (_entities)
+                if (_entities.TryGetValue(type, out mapper))
                 {
-                    if (!_entities.TryGetValue(type, out mapper))
-                        return this.BuildAddEntityMapper(type);
+                    return mapper;
                 }
+
+                if(_buildEntities.TryGetValue(type, out EntityMapper buildMapper))
```
Comment (einarmo) [inline LiteDB/Client/Mapper/BsonMapper.cs:257]: I think this case is impossible, and shouldn't be necessary to check.

**Review by einarmo — COMMENTED** [review]
I think this makes sense, though the whole thing is IMO a little unpleasant.

Probably better than my solution in terms of performance.

One thing I'm still unsure of is whether it is actually safe to concurrently insert into a dictionary while reading from it on another thread, I think there is a chance it fails, if the underlying storage needs to grow, but I'm not familiar enough with the details of Dictionary to say for sure.

**Review by SkitX1337 — APPROVED** [review]

File: LiteDB/Client/Mapper/BsonMapper.cs [hunk 2]
```diff
@@ -30,7 +30,12 @@ public partial class BsonMapper
         /// Mapping cache between Class/BsonDocument
         /// </summary>
         private readonly Dictionary<Type, EntityMapper> _entities = new Dictionary<Type, EntityMapper>();
-
+        
+        /// <summary>
+        /// Unfinished mapping cache between Class/BsonDocument
+        /// </summary>
+        private readonly Dictionary<Type, EntityMapper> _buildEntities = new Dictionary<Type, EntityMapper>();
```
Comment (pictos) [inline LiteDB/Client/Mapper/BsonMapper.cs:37]: how about using ConcurrentDictionary?

Comment (JKamsker) [reply LiteDB/Client/Mapper/BsonMapper.cs:37]: We don't need concurrent access to this because it is only ever used in building the type mapping, which is always happening in the same thread.

File: LiteDB/Client/Mapper/BsonMapper.cs [hunk 3]
```diff
@@ -235,13 +242,30 @@ internal EntityMapper GetEntityMapper(Type type)
         {
             //TODO: needs check if Type if BsonDocument? Returns empty EntityMapper?
 
-            if (!_entities.TryGetValue(type, out EntityMapper mapper))
+            if (_entities.TryGetValue(type, out EntityMapper mapper))
+            {
+                return mapper;
+            }
+
+            lock (_entities)
```
Comment (pictos) [inline LiteDB/Client/Mapper/BsonMapper.cs:250]: You mentioned that is not needed to use `ConcurrentDictionary`, but we need a lock here in order to access and update its values (for both), are you sure isn't better to use that collection and avoid the `lock` here?

Comment (JKamsker) [reply LiteDB/Client/Mapper/BsonMapper.cs:250]: In the best case (which happens 99% of the time), we don`t lock. Only initially, when first creating the mapping, we need the lock. 

In addidtion to that, this behaviour is the same as the original code before the [bugfix that caused this bug](https://github.com/mbdavid/LiteDB/pull/2493)

**Review by pictos — APPROVED** [review]

File: LiteDB/Client/Mapper/BsonMapper.cs [hunk 4]
```diff
@@ -30,7 +30,12 @@ public partial class BsonMapper
         /// Mapping cache between Class/BsonDocument
         /// </summary>
         private readonly Dictionary<Type, EntityMapper> _entities = new Dictionary<Type, EntityMapper>();
```
Comment (vonzshik) [inline LiteDB/Client/Mapper/BsonMapper.cs:32]: I'm not sure it's a good idea to allow concurrent access to `Dictionary`, given that [it's not thread-safe](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-8.0#thread-safety) and there is possible concurrent read and write happening.

Comment (JKamsker) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: https://github.com/mbdavid/LiteDB/pull/2538/files/4bdb4b700d0ed60e72656c84dc674a2c6004682e#r1778334038

Comment (JKamsker) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: No. The original issue was actually due to recursive access. That's a difference.

Comment (vonzshik) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: I'm talking about https://github.com/mbdavid/LiteDB/issues/2536. It's possible to have multiple threads doing concurrent read (which is fine) but at the same time one thread will be writing to that dictionary, and this situation isn't thread safe.

Comment (JKamsker) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: Any access to _buildEntities is guarded by a lock

https://github.com/JKamsker/LiteDB/blob/4bdb4b700d0ed60e72656c84dc674a2c6004682e/LiteDB/Client/Mapper/BsonMapper.cs#L250-L269

Comment (vonzshik) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: I'm not talking about `_buildEntities` but `_entities`

Comment (JKamsker) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: The double-checked locking has always been there and i cant find any issues concerning this regard. https://github.com/mbdavid/LiteDB/pull/2493/files#diff-db4637fbacd6bcf21b8bc9df379f084f98e4cac70c3d9858bc8df4d28bdbe7efL234

Comment (vonzshik) [reply LiteDB/Client/Mapper/BsonMapper.cs:32]: Here you go #2563, repro which throws nre
